# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: node:5.11.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - npm --version
          - npm install
          - pushd restApi && npm install && popd
          - npm test
